name: Build container

on:
  push:
    paths:
      - 'Dockerfile'
  schedule:
    - cron: '0 0 */7 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🍽️ Getting code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: 🍿 Build and push Docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: patschi/gitlab-runner-hetzner
          tags: alpine
          add_git_labels: true
